#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_border                off
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0

# Rules
yabai -m rule --add app=System\ Preferences manage=off
yabai -m rule --add app=System\ Settings manage=off
yabai -m rule --add app=AnyConnect manage=off

echo "yabai configuration loaded.."
